# Generated by Django 5.1.4 on 2024-12-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teléfono', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('en_servicio', models.BooleanField()),
                ('detalles', models.TextField()),
                ('contrasena_ingreso', models.CharField(max_length=100)),
                ('propietario', models.TextField()),
                ('imei', models.TextField()),
            ],
        ),
    ]
