# Generated by Django 5.1.4 on 2024-12-19 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablaPrincipal', '0002_rename_teléfono_producto_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='inventario',
        ),
    ]
