# Generated by Django 5.1.4 on 2025-07-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablaPrincipal', '0003_rename_producto_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='baseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='inventario',
            new_name='inventarioTel',
        ),
    ]
