# Generated by Django 5.1.4 on 2025-07-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablaPrincipal', '0004_baseitem_rename_inventario_inventariotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipoPcCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('en_servicio', models.BooleanField()),
                ('detalles', models.CharField(max_length=250)),
                ('modelo', models.CharField(max_length=25)),
                ('departamento', models.CharField(max_length=15)),
                ('serie', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('en_servicio', models.BooleanField()),
                ('detalles', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='muebles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('en_servicio', models.BooleanField()),
                ('detalles', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='operaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('en_servicio', models.BooleanField()),
                ('detalles', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('serie', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='uniformes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('en_servicio', models.BooleanField()),
                ('detalles', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('en_servicio', models.BooleanField()),
                ('detalles', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='baseItem',
        ),
    ]
