# Generated by Django 5.0.2 on 2025-07-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablaPrincipal', '0005_equipopccom_herramienta_muebles_operaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipopccom',
            name='detalles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='detalles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='muebles',
            name='detalles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='operaciones',
            name='detalles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uniformes',
            name='detalles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehiculos',
            name='detalles',
            field=models.TextField(),
        ),
    ]
