# Generated by Django 5.1.4 on 2025-07-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablaPrincipal', '0007_equipopccom_fecha_herramienta_fecha_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='equipoPcCom',
        ),
    ]
