# Generated by Django 5.1.4 on 2025-07-12 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='equipoPcCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propietario', models.CharField(max_length=50)),
                ('en_servicio', models.BooleanField()),
                ('detalles', models.TextField()),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('marca', models.CharField(max_length=25)),
                ('departamento', models.CharField(max_length=15)),
                ('imei', models.CharField(max_length=50)),
                ('contrasena_ingreso', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
